### ISSUE TITLE
Wrong domain for sitemap on Vercel

### ISSUE THREAD

**Issue by learntheropes** [harlan-zw/nuxt-simple-robots#30]
### Describe the bug

I have the following settings:

```js
  const excludedRoutes = ['/es/admin', '/es/dashboard', '/en/admin', '/en/dashboard', '/it/admin', '/it/dashboard' ]

  robots: {
    disallow: excludedRoutes,
  },

  sitemap: {
    xsl: false,
    exclude: excludedRoutes,
    autoI18n: true
  },
```

The project is deployed on Vercel where I also have the following env variable:
```
NUXT_PUBLIC_SITE_URL = https://anybtcpay.learntheropes.xyz
```
The generated robots includes a sitemap url, which is fine.

However when the app is deployed on vercel it gets the domain from `VERCEL_URL` [System Environment Variables](https://vercel.com/docs/projects/environment-variables/system-environment-variables#system-environment-variables) instead of the custom domain that I provided with `NUXT_PUBLIC_SITE_URL`.

So the final provided sitemap url is https://anybtcpay-fs9bfjagm-learntheropes.vercel.app/sitemap_index.xml (deployment domain)
instead of https://anybtcpay.learntheropes.xyz/sitemap_index.xml (custom domain)

The workaround is to provide the sitemap url manually as follows:
```
  robots: {
    disallow: excludedRoutes,
   sitemap: `https://anybtcpay.learntheropes.xyz/sitemap_index.xml`
  },
```
But the default,  should check for `NUXT_PUBLIC_SITE_URL` before `VERCEL_URL`

### System / Nuxt Info

```Shell
- Operating System: Linux
- Node Version:     v18.17.0
- Nuxt Version:     3.7.0
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  npm@9.6.7
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
```

**Comment by harlan-zw** [comment]
Hey @learntheropes, it should definitely prioritize the Nuxt environment variables over the `VERCEL_URL`.

Are you able to deploy it with the config:

```ts
export default defineNuxtConfig({
  site: {
    debug: true
  }
})
```

This will let me see how it's being resolved by visiting `/api/__site-config__/debug`.

If you need a workaround, this should work.

```ts
export default defineNuxtConfig({
  site: {
    name: process.env.NUXT_PUBLIC_SITE_URL
  }
})
```

**Comment by learntheropes** [comment]
I enabled debug as you asked and commented out my workaround to let you investigate, as you can see here https://github.com/learntheropes/btcpay-any/blob/d96fd4e887d97adf1d66c8f324a51dbf597b9e65/nuxt.config.js#L114

For some reason now the robots is showing the correct sitemap domain (`NUXT_PUBLIC_SITE_URL`)

I don't know how this happens, since nothing changed in my code.

I think we can close this issue for now.

**Comment by harlan-zw** [comment]
Strange indeed, please let me know if you spot anything else! Appreciate the detailed issues

**Comment by learntheropes** [comment]
@harlan-zw can you please debug it?

I have the same issue again.

The link is https://www.anybtcpay.com/robots.txt

As you can check, the robots set a sitemap to the vercel subdomain.

The vercel subdomain does not exist anymore in my domain's configuration, where I now have www.anybtcpay.com and anybtcpay.com (that redirects to www).

This in my `nuxt.config`:
```js
  site: {
    name: process.env.NUXT_PUBLIC_SITE_URL,
    debug: true
  },
  sitemap: {
    xsl: false,
    autoI18n: true
  },
```

**Comment by learntheropes** [comment]
For your information, I had to move the website of the previous message to https://test.anybtcpay.com/robots.txt
You can debug there. The issue is still the same

**Comment by harlan-zw** [comment]
Hey, this is quite strange. Can you try bumping your dependencies (nuxt-simple-robots and nuxt-simple-sitemap), if it doesn't fix it, if you re-deploy, it will give me more data.

**Comment by learntheropes** [comment]
I uninstalled the modules and reinstalled.
I switched from `nuxi build` to `nuxi generate`.
I changed from:
```js
export default defineNuxtConfig({
  site: {
    name: process.env.NUXT_PUBLIC_SITE_URL,
    debug: true
  }
})
```
to:
```js
export default defineNuxtConfig({
  site: {
    name: process.env.CUSTOM_VARIABLE_THAT_POINT_TO_MY_DOMAIN,
    debug: true
  }
})
```
But the issue is still the same.

**Comment by harlan-zw** [comment]
Oh right, I think the issue is that the config should be:

```diff
export default defineNuxtConfig({
  site: {
-   name: process.env.NUXT_PUBLIC_SITE_URL,
+   url: process.env.NUXT_PUBLIC_SITE_URL,
    debug: true
  }
})
```

The error likely came up as it's not using inferring the `NUXT_PUBLIC_SITE_URL` by default for some reason (so a different bug). Will look into this

**Comment by learntheropes** [comment]
Oh, sorry. I made that change. Still the same issue.

**Comment by harlan-zw** [comment]
Can you try just explicitly setting the `url` to help me diagnose what may be going wrong?

```ts
export default defineNuxtConfig({
  site: {
    url: 'https://www.anybtcpay.com',
    debug: true
  }
})
```

**Comment by learntheropes** [comment]
This way it works correctly.

**Comment by harlan-zw** [comment]
The underlying issue for this _should_ be resolved in 3.1.6, environment variables should always have the highest priority.

Some work was done on nuxt-site-config to make this better.
